# Generated by Django 3.1.6 on 2021-03-31 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CreateQuiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='response_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateQuiz.option_data')),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateQuiz.question_data')),
                ('quizid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateQuiz.quiz_data')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
