# Generated by Django 3.1.6 on 2021-03-31 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiztitle', models.CharField(max_length=40)),
                ('quizid', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=1000)),
                ('response_status', models.BooleanField(default=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtitle', models.CharField(max_length=500)),
                ('qtype', models.BooleanField(default=False)),
                ('quizid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateQuiz.quiz_data')),
            ],
        ),
        migrations.CreateModel(
            name='option_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=500)),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateQuiz.question_data')),
                ('quizid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateQuiz.quiz_data')),
            ],
        ),
    ]
