# Generated by Django 3.1.6 on 2021-03-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_data',
            name='quizid',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
