# Generated by Django 3.1.6 on 2021-03-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_quiz_data_quizid'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_data',
            name='response_status',
            field=models.BooleanField(default=True),
        ),
    ]
