# Generated by Django 3.1.6 on 2021-03-31 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQuiz', '0001_initial'),
        ('userlogin', '0003_quiz_data_response_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_data',
            name='quizid',
        ),
        migrations.RemoveField(
            model_name='quiz_data',
            name='username',
        ),
        migrations.AlterField(
            model_name='response_data',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateQuiz.option_data'),
        ),
        migrations.AlterField(
            model_name='response_data',
            name='questionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateQuiz.question_data'),
        ),
        migrations.AlterField(
            model_name='response_data',
            name='quizid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateQuiz.quiz_data'),
        ),
        migrations.DeleteModel(
            name='option_data',
        ),
        migrations.DeleteModel(
            name='Question_data',
        ),
        migrations.DeleteModel(
            name='quiz_data',
        ),
    ]
