# Generated by Django 3.1.6 on 2021-03-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0004_auto_20210331_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='response_data',
        ),
    ]
